require("config.lazy")
require("config.dracula")
require("config.general")
require("config.lsp")
require("config.autopairs")
require("config.formatter")
require("config.telescope")
require("config.iron")
require("config.comment")
-- require("config.lualine")
require("config.neo_tree")
